#!/usr/bin/env bash

git clone -b v0.11.0 git@github.com:neovim/neovim.git $HOME/personal/neovim
sudo dnf install ninja-build cmake gcc make gettext curl glibc-gconv-extra

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

